version: "3.6"

services:
  report-service:
    image: paxapp/pax-report:latest
    volumes:
      - ".:/app"
    ports:
      - 5005:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=mysql+pymysql://paxadmin:LpvuM1QnfcxOOVeNQQvl@pax-database.cd0j8avv0tgq.sa-east-1.rds.amazonaws.com:3306/paxdb
      - DATABASE_TEST_URL=mysql+pymysql://username:password@localhost:3306/pax
    command: python manage.py run -h 0.0.0.0
