version: "3.6"

services:
  report-service:
    build:
    context: ./services/report
    dockerfile: Dockerfile
    volumes:
      - "./services/report:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init
